#!/bin/bash
#    Copyright 2013 Red Hat, Inc. and/or its affiliates.
#
#    This file is part of jcliff.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
set -euo pipefail
readonly IFS=$'\n\t'

readonly JBOSS_HOME=${JBOSS_HOME}
readonly JCLIFF_HOME=${JCLIFF_HOME:-"$(pwd)"}
readonly JBOSS_CONTROLLER_HOST=${JBOSS_CONTROLLER:-'localhost'}
readonly JBOSS_CONTROLLER_PORT=${JBOSS_PORT:-'9990'}
readonly JCLIFF_RULES_DIR=${JCLIFF_RULES_DIR:-"$(pwd)/src/main/resources/"}
readonly JAVA_HOME=${JAVA_HOME:-''}

if [ ! -z "${JAVA_HOME}" ]; then
  JAVA=${JAVA_HOME}/bin/java
else
  JAVA=$(which java)
fi

if [ ! -d "${JBOSS_HOME}" ]; then
  echo "The provided JBOSS_HOME is invalid: '${JBOSS_HOME}'."
  exit 1
fi

CLASSPATH=$(echo "${JCLIFF_HOME}"/target/jcliff-*.jar)
readonly dependencies_dir="${JCLIFF_HOME}/target/dependency/"
for jar in ${dependencies_dir}/*.jar ; do
    CLASSPATH="${jar}:${CLASSPATH}"
done

"${JAVA}" -classpath "${CLASSPATH}" 'com.redhat.jcliff.Main' \
          --cli="${JBOSS_HOME}/bin/jboss-cli.sh" \
          --controller="${JBOSS_CONTROLLER_HOST}:${JBOSS_CONTROLLER_PORT}" \
          --ruledir="${JCLIFF_RULES_DIR}"     \
          ${@}
