name: Release Jcliff

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release Jcliff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Tag Version
        id: get_version
        run: echo ::set-output name=TAG_VERSION::${GITHUB_REF#refs/tags/}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven build and assembly
        run: mvn -B verify --file pom.xml
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            target/*.tar.gz
            target/rpm/jcliff/RPMS/noarch/*.rpm
          body: "Release ${{ steps.get_version.outputs.TAG_VERSION }}"
      - name: Homebrew Release
        env:
          HOMEBREW_TAP_REPO: ${{ secrets.HOMEBREW_REPOSITORY }}
          BREW_USER: ${{ secrets.BREW_USER }}
          BREW_TOKEN: ${{ secrets.BREW_TOKEN }}
        run: |
          set -e

          JCLIFF_TAG=${{ steps.get_version.outputs.TAG_VERSION }}
          HOMEBREW_TAP_REPO="${HOMEBREW_TAP_REPO:-redhat-cop/homebrew-redhat-cop}"
          REPO_NAME=$(basename $HOMEBREW_TAP_REPO)

          SHA256=`sha256sum target/jcliff-${JCLIFF_TAG:1}-dist.tar.gz | cut -f1 -d ' '`
          URL="https://github.com/bserdar/jcliff/releases/download/${JCLIFF_TAG}/jcliff-${JCLIFF_TAG:1}-dist.tar.gz"

          rm -rf $REPO_NAME

          git clone https://github.com/${HOMEBREW_TAP_REPO}.git

          sed -i -e 's|^  url.*|  url "'"$URL"'"|g' $REPO_NAME/Formula/jcliff.rb
          sed -i -e 's|^  sha256.*|  sha256 "'"$SHA256"'"|g' $REPO_NAME/Formula/jcliff.rb

          cd $(basename $HOMEBREW_TAP_REPO)

          git config user.name "Andrew Block"
          git config user.email "andy.block@gmail.com"

          git add Formula/jcliff.rb
          git commit -m "jcliff ${JCLIFF_TAG} release"

          if [[ ! -z $BREW_USER && ! -z $BREW_TOKEN ]]; then
            git push https://${BREW_USER}:${BREW_GITHUB_TOKEN}@github.com/${HOMEBREW_TAP_REPO}.git
          else
            echo "BREW_USER and BREW_TOKEN variables not set. Skipping push..."
          fi
