name: Release Jcliff

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release Jcliff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Tag Version
        id: get_version
        run: echo ::set-output name=TAG_VERSION::${GITHUB_REF#refs/tags/}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven build and assembly
        run: mvn -B verify --file pom.xml
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            target/*.tar.gz
            target/rpm/jcliff/RPMS/noarch/*.rpm
          body: "Release ${{ steps.get_version.outputs.TAG_VERSION }}"
